#include "js_function.h"

void *fn_console_log = "console.log";

void *fn_array_at = "Array.at"; // todo
void *fn_array_concat = "Array.concat"; // todo
void *fn_array_copywithin = "Array.copyWithin"; // todo
void *fn_array_entries = "Array.entries"; // todo
void *fn_array_every = "Array.every"; // todo
void *fn_array_fill = "Array.fill"; // todo
void *fn_array_filter = "Array.filter"; // todo
void *fn_array_find = "Array.find"; // todo
void *fn_array_findindex = "Array.findIndex"; // todo
void *fn_array_findlast = "Array.findLast"; // todo
void *fn_array_findlastindex = "Array.findLastIndex"; // todo
void *fn_array_flat = "Array.flat"; // todo
void *fn_array_flatmap = "Array.flatMap"; // todo
void *fn_array_foreach = "Array.forEach"; // todo
void *fn_array_from = "Array.from"; // todo
void *fn_array_includes = "Array.includes"; // todo
void *fn_array_indexof = "Array.indexOf"; // todo
void *fn_array_isarray = "Array.isArray"; // todo
void *fn_array_join = "Array.join"; // todo
void *fn_array_keys = "Array.keys"; // todo
void *fn_array_lastindexof = "Array.lastIndexOf"; // todo
void *fn_array_map = "Array.map"; // todo
void *fn_array_of = "Array.of"; // todo
void *fn_array_pop = "Array.pop"; // todo
void *fn_array_push = "Array.push"; // todo
void *fn_array_reduce = "Array.reduce"; // todo
void *fn_array_reduceright = "Array.reduceRight"; // todo
void *fn_array_reverse = "Array.reverse"; // todo
void *fn_array_shift = "Array.shift"; // todo
void *fn_array_slice = "Array.slice"; // todo
void *fn_array_some = "Array.some"; // todo
void *fn_array_sort = "Array.sort"; // todo
void *fn_array_splice = "Array.splice"; // todo
void *fn_array_tostring = "Array.toString"; // todo
void *fn_array_unshift = "Array.unshift"; // todo
void *fn_array_valueof = "Array.valueOf"; // todo
void *fn_array_with = "Array.with"; // todo

void *fn_boolean_tostring = "Boolean.toString"; // todo
void *fn_boolean_valueof = "Boolean.valueOf"; // todo

void *fn_date_getdate = "Date.getDate"; // todo
void *fn_date_getday = "Date.getDay"; // todo
void *fn_date_getfullyear = "Date.getFullYear"; // todo
void *fn_date_gethours = "Date.getHours"; // todo
void *fn_date_getmilliseconds = "Date.getMilliseconds"; // todo
void *fn_date_getminutes = "Date.getMinutes"; // todo
void *fn_date_getmonth = "Date.getMonth"; // todo
void *fn_date_getseconds = "Date.getSeconds"; // todo
void *fn_date_gettime = "Date.getTime"; // todo
void *fn_date_gettimezoneoffset = "Date.getTimezoneOffset"; // todo
void *fn_date_getutcdate = "Date.getUTCDate"; // todo
void *fn_date_getutcday = "Date.getUTCDay"; // todo
void *fn_date_getutcfullyear = "Date.getUTCFullYear"; // todo
void *fn_date_getutchours = "Date.getUTCHours"; // todo
void *fn_date_getutcmilliseconds = "Date.getUTCMilliseconds"; // todo
void *fn_date_getutcminutes = "Date.getUTCMinutes"; // todo
void *fn_date_getutcmonth = "Date.getUTCMonth"; // todo
void *fn_date_getutcseconds = "Date.getUTCSeconds"; // todo
void *fn_date_getyear = "Date.getYear"; // todo
void *fn_date_now = "Date.now"; // todo
void *fn_date_parse = "Date.parse"; // todo
void *fn_date_setdate = "Date.setDate"; // todo
void *fn_date_setfullyear = "Date.setFullYear"; // todo
void *fn_date_sethours = "Date.setHours"; // todo
void *fn_date_setmilliseconds = "Date.setMilliseconds"; // todo
void *fn_date_setminutes = "Date.setMinutes"; // todo
void *fn_date_setmonth = "Date.setMonth"; // todo
void *fn_date_setseconds = "Date.setSeconds"; // todo
void *fn_date_settime = "Date.setTime"; // todo
void *fn_date_setutcdate = "Date.setUTCDate"; // todo
void *fn_date_setutcfullyear = "Date.setUTCFullYear"; // todo
void *fn_date_setutchours = "Date.setUTCHours"; // todo
void *fn_date_setutcmilliseconds = "Date.setUTCMilliseconds"; // todo
void *fn_date_setutcminutes = "Date.setUTCMinutes"; // todo
void *fn_date_setutcmonth = "Date.setUTCMonth"; // todo
void *fn_date_setutcseconds = "Date.setUTCSeconds"; // todo
void *fn_date_setyear = "Date.setYear"; // todo
void *fn_date_todatestring = "Date.toDateString"; // todo
void *fn_date_togmtstring = "Date.toGMTString"; // todo
void *fn_date_toisostring = "Date.toISOString"; // todo
void *fn_date_tojson = "Date.toJSON"; // todo
void *fn_date_tolocaledatestring = "Date.toLocaleDateString"; // todo
void *fn_date_tolocaletimestring = "Date.toLocaleTimeString"; // todo
void *fn_date_tolocalestring = "Date.toLocaleString"; // todo
void *fn_date_tostring = "Date.toString"; // todo
void *fn_date_totimestring = "Date.toTimeString"; // todo
void *fn_date_toutcstring = "Date.toUTCString"; // todo
void *fn_date_utc = "Date.UTC"; // todo
void *fn_date_valueof = "Date.valueOf"; // todo

void *fn_json_parse = "JSON.parse"; // todo
void *fn_json_stringify = "JSON.stringify"; // todo

void *fn_math_abs = "Math.abs";
void *fn_math_acos = "Math.acos";     // todo
void *fn_math_acosh = "Math.acosh";   // todo
void *fn_math_asin = "Math.asin";     // todo
void *fn_math_asinh = "Math.asinh";   // todo
void *fn_math_atan = "Math.atan";     // todo
void *fn_math_atan2 = "Math.atan2";   // todo
void *fn_math_atanh = "Math.atanh";   // todo
void *fn_math_cbrt = "Math.cbrt";     // todo
void *fn_math_ceil = "Math.ceil";     // todo
void *fn_math_clz32 = "Math.clz32";   // todo
void *fn_math_cos = "Math.cos";       // todo
void *fn_math_cosh = "Math.cosh";     // todo
void *fn_math_exp = "Math.exp";       // todo
void *fn_math_expm1 = "Math.expm1";   // todo
void *fn_math_floor = "Math.floor";   // todo
void *fn_math_fround = "Math.fround"; // todo
void *fn_math_log = "Math.log";       // todo
void *fn_math_log10 = "Math.log10";   // todo
void *fn_math_log1p = "Math.log1p";   // todo
void *fn_math_log2 = "Math.log2";
void *fn_math_max = "Math.max";       // todo
void *fn_math_min = "Math.min";       // todo
void *fn_math_pow = "Math.pow";       // todo
void *fn_math_random = "Math.random"; // todo
void *fn_math_round = "Math.round";   // todo
void *fn_math_sign = "Math.sign";     // todo
void *fn_math_sin = "Math.sin";       // todo
void *fn_math_sinh = "Math.sinh";     // todo
void *fn_math_sqrt = "Math.sqrt";
void *fn_math_tan = "Math.tan";     // todo
void *fn_math_tanh = "Math.tanh";   // todo
void *fn_math_trunc = "Math.trunc"; // todo

void *fn_number_isfinite = "Number.isFinite"; // todo
void *fn_number_isinteger = "Number.isInteger"; // todo
void *fn_number_isnan = "Number.isNaN"; // todo
void *fn_number_issafeinteger = "Number.isSafeInteger"; // todo
void *fn_number_parsefloat = "Number.parseFloat"; // todo
void *fn_number_parseint = "Number.parseInt"; // todo
void *fn_number_toexponential = "Number.toExponential"; // todo
void *fn_number_tofixed = "Number.toFixed"; // todo
void *fn_number_tolocalestring = "Number.toLocaleString"; // todo
void *fn_number_toprecision = "Number.toPrecision"; // todo
void *fn_number_tostring = "Number.toString"; // todo
void *fn_number_valueof = "Number.valueOf"; // todo

void *fn_object_keys = "Object.keys"; // todo
void *fn_object_tostring = "Object.toString"; // todo
void *fn_object_valueof = "Object.valueOf"; // todo

void *fn_string_charat = "String.charAt";
void *fn_string_charcodeat = "String.charCodeAt";
void *fn_string_concat = "String.concat"; // todo
void *fn_string_endswith = "String.endsWith"; // todo
void *fn_string_fromcharcode = "String.fromCharCode"; // todo
void *fn_string_includes = "String.includes"; // todo
void *fn_string_indexof = "String.indexOf"; // todo
void *fn_string_lastindexof = "String.lastIndexOf"; // todo
void *fn_string_localecompare = "String.localeCompare"; // todo
void *fn_string_match = "String.match"; // todo
void *fn_string_repeat = "String.repeat"; // todo
void *fn_string_replace = "String.replace"; // todo
void *fn_string_replaceall = "String.replaceAll"; // todo
void *fn_string_search = "String.search"; // todo
void *fn_string_slice = "String.slice"; // todo
void *fn_string_split = "String.split"; // todo
void *fn_string_startswith = "String.startsWith"; // todo
void *fn_string_substr = "String.substr";
void *fn_string_substring = "String.substring"; // todo
void *fn_string_tolocalelowercase = "String.toLocaleLowerCase"; // todo
void *fn_string_tolocaleuppercase = "String.toLocaleUpperCase"; // todo
void *fn_string_tolowercase = "String.toLowerCase"; // todo
void *fn_string_tostring = "String.toString"; // todo
void *fn_string_touppercase = "String.toUpperCase"; // todo
void *fn_string_trim = "String.trim"; // todo
void *fn_string_trimend = "String.trimEnd"; // todo
void *fn_string_trimstart = "String.trimStart"; // todo
void *fn_string_valueof = "String.valueOf"; // todo
